/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.enade.DAO.CursoDAO;
import br.com.enade.DAO.DisciplinaDAO;
import br.com.enade.bean.Curso;
import br.com.enade.bean.Disciplina;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author silas
 */
public class TelaDisciplina extends javax.swing.JInternalFrame {


    /**
     * Creates new form TelaCadastroDisciplina
     */
    public TelaDisciplina() {
        initComponents();
         DefaultTableModel modelo = (DefaultTableModel) jTDisciplina.getModel();
        jTDisciplina.setRowSorter(new TableRowSorter(modelo));
        txtCod_Disciplina.setEditable(false);
        

        

        
        readJTable();
    }
    
    
    
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTDisciplina.getModel();
        modelo.setNumRows(0);
        DisciplinaDAO pdao = new DisciplinaDAO();
        

        for (Disciplina d : pdao.read()) {

            modelo.addRow(new Object[]{
                d.getCod_disciplina(),
                d.getNome_disciplina(),
                d.getCurso().getNome_curso()
                
            });

        }

    }
    
    
    
       public void readJTableForDesc(String Nome) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTDisciplina.getModel();
        modelo.setNumRows(0);
        DisciplinaDAO pdao = new DisciplinaDAO();
        
        

        for (Disciplina d : pdao.readForDesc(Nome)) {

            modelo.addRow(new Object[]{
                d.getCod_disciplina(),
                d.getNome_disciplina(),
                d.getCurso().getNome_curso()

            });

            }
        
       }
       
       
       
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome_Disciplina = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCod_Disciplina = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDisciplina = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtListar = new javax.swing.JTextField();
        btnListar = new javax.swing.JButton();
        cbCurso = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/stop.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Disciplina");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("NOME");

        jLabel3.setText("CÓDIGO");

        txtCod_Disciplina.setBackground(new java.awt.Color(204, 204, 204));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/application_form.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/add.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/application_form_delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/application_edit.png"))); // NOI18N
        btnAlterar.setText("Editar");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jTDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDisciplinaMouseClicked(evt);
            }
        });
        jTDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTDisciplina);
        if (jTDisciplina.getColumnModel().getColumnCount() > 0) {
            jTDisciplina.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTDisciplina.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTDisciplina.getColumnModel().getColumn(2).setPreferredWidth(120);
        }

        jLabel4.setText("Pesquisar Disciplina");

        txtListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListarActionPerformed(evt);
            }
        });
        txtListar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtListarKeyReleased(evt);
            }
        });

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images/application_form_magnify.png"))); // NOI18N
        btnListar.setText("Buscar");
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        cbCurso.setToolTipText("");
        cbCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbCurso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbCursoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("CURSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(323, 323, 323)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCod_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(txtNome_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(8, 8, 8)
                                .addComponent(txtListar, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setBounds(500, 115, 617, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        //TelaPrincipal.cadastro=true;
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jbSairActionPerformed

    private void txtListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        LimparCampos();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
           try {
            if(txtNome_Disciplina.getText().equals("")){
                JOptionPane.showMessageDialog(jTDisciplina,"Preencha todos os campos");
                return;
            }
            
        Disciplina d = new Disciplina();
        Curso obj_curso = new Curso();
        DisciplinaDAO dao = new DisciplinaDAO();

        d.setNome_disciplina(txtNome_Disciplina.getText());
        
        //Recebe os dados do Combobox
        obj_curso = (Curso) cbCurso.getSelectedItem();
        d.setCurso(obj_curso);
        
        
        dao.create(d);

        txtCod_Disciplina.setText("");
        txtNome_Disciplina.setText("");

        readJTable();

       // LimparCampos(); //Após cadastrar, Método chamado para limpar os campos.

            
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar, Tente novamente ou consulte o administrador do sistema!");
        } catch (Exception ex) {
            Logger.getLogger(TelaDisciplina.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        
        if (jTDisciplina.getSelectedRow() != -1) {
               
               Disciplina d = new Disciplina();
               DisciplinaDAO dao = new DisciplinaDAO();
               
               d.setNome_disciplina(txtNome_Disciplina.getText());
               Curso obj_curso = (Curso) cbCurso.getSelectedItem();
               d.setCurso(obj_curso);

               d.setCod_disciplina((int) jTDisciplina.getValueAt(jTDisciplina.getSelectedRow(), 0));
               dao.update(d);

               
               txtCod_Disciplina.setText("");
               txtNome_Disciplina.setText("");
               
               readJTable();
                } else {
            JOptionPane.showMessageDialog(null, "Selecione uma disciplina para edição!.");
        
        }              
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        readJTableForDesc(txtListar.getText());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        
        if (jTDisciplina.getSelectedRow() != -1) {

            Disciplina d = new Disciplina();
            DisciplinaDAO dao = new DisciplinaDAO();

            d.setCod_disciplina((int) jTDisciplina.getValueAt(jTDisciplina.getSelectedRow(), 0));
            
            try {
                dao.delete(d);
            } catch (SQLException ex) {
                Logger.getLogger(TelaDisciplina.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtCod_Disciplina.setText("");
            txtNome_Disciplina.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma disciplina para excluir.");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jTDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDisciplinaKeyReleased
        // TODO add your handling code here:
        //Key_Relsease pelo Jtable
         if (jTDisciplina.getSelectedRow() != -1) {

            txtNome_Disciplina.setText(jTDisciplina.getValueAt(jTDisciplina.getSelectedRow(), 1).toString());
        }
        
        
    }//GEN-LAST:event_jTDisciplinaKeyReleased

    private void jTDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDisciplinaMouseClicked
        // TODO add your handling code here:
        
        //Mouse CLicked - Evento para Jtable
        
        if (jTDisciplina.getSelectedRow() != -1) {

            txtNome_Disciplina.setText(jTDisciplina.getValueAt(jTDisciplina.getSelectedRow(), 1).toString());
            
        }
    }//GEN-LAST:event_jTDisciplinaMouseClicked

    private void cbCursoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbCursoAncestorAdded
        // TODO add your handling code here:
        
        
        CursoDAO dao = new CursoDAO();

        List<Curso> list = dao.read();
         //Remove todos os iteis de um Combox, para nao ocorrer dados duplicados
         cbCurso.removeAll();
         for(Curso c: list){
             cbCurso.addItem(c);
         }
         
         
    }//GEN-LAST:event_cbCursoAncestorAdded

    private void txtListarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtListarKeyReleased

    }//GEN-LAST:event_txtListarKeyReleased
    
    private void LimparCampos(){
      txtCod_Disciplina.setText(null);
      txtNome_Disciplina.setText(null);
      txtListar.setText(null);
      ((DefaultTableModel)jTDisciplina.getModel()).setNumRows(0);

      
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDisciplina;
    private javax.swing.JButton jbSair;
    private javax.swing.JTextField txtCod_Disciplina;
    private javax.swing.JTextField txtListar;
    private javax.swing.JTextField txtNome_Disciplina;
    // End of variables declaration//GEN-END:variables
}
